### PR TITLE
Generalize affine distributions to negative scales

### LINKED ISSUE #1653: Affine distributions with useless requirements ?
Hey, 
Why is it so that i cannot express an affine transformation of a gamma distribution ? 

```julia
julia> X = Normal(0,1)
Normal{Float64}(μ=0.0, σ=1.0)

julia> Y = Gamma(1,1)
Gamma{Float64}(α=1.0, θ=1.0)

julia> -X
ERROR: MethodError: no method matching -(::Normal{Float64})
Closest candidates are:
  -(::UnivariateDistribution, ::Real) at C:\Users\lrnv\.julia\packages\Distributions\gggmX\src\univariate\locationscale.jl:146    
  -(::T1, ::DataValues.DataValue{T2}) where {T1, T2} at C:\Users\lrnv\.julia\packages\DataValues\N7oeL\src\scalar\operations.jl:75
  -(::Any, ::ChainRulesCore.AbstractThunk) at C:\Users\lrnv\.julia\packages\ChainRulesCore\C73ay\src\tangent_types\thunks.jl:35   
  ...
Stacktrace:
 [1] top-level scope
   @ REPL[426]:1

julia> (-1)*X
Normal{Float64}(μ=-0.0, σ=1.0)

julia> -Y
ERROR: MethodError: no method matching -(::Gamma{Float64})
Closest candidates are:
  -(::UnivariateDistribution, ::Real) at C:\Users\lrnv\.julia\packages\Distributions\gggmX\src\univariate\locationscale.jl:146        
  -(::T1, ::DataValues.DataValue{T2}) where {T1, T2} at C:\Users\lrnv\.julia\packages\DataValues\N7oeL\src\scalar\operations.jl:75    
  -(::Any, ::ChainRulesCore.AbstractThunk) at C:\Users\lrnv\.julia\packages\ChainRulesCore\C73ay\src\tangent_types\thunks.jl:35       
  ...
Stacktrace:
 [1] top-level scope
   @ REPL[428]:1

julia> (-1)*Y
ERROR: DomainError with -1:
AffineDistribution: the condition σ > zero(σ) is not satisfied.
Stacktrace:
 [1] #77
   @ C:\Users\lrnv\.julia\packages\Distributions\gggmX\src\univariate\locationscale.jl:53 [inlined]
 [2] check_args
   @ C:\Users\lrnv\.julia\packages\Distributions\gggmX\src\utils.jl:89 [inlined]
 [3] #AffineDistribution#76
   @ C:\Users\lrnv\.julia\packages\Distributions\gggmX\src\univariate\locationscale.jl:53 [inlined]
 [4] AffineDistribution
   @ C:\Users\lrnv\.julia\packages\Distributions\gggmX\src\univariate\locationscale.jl:53 [inlined]
 [5] *(x::Int64, d::Gamma{Float64})
   @ Distributions C:\Users\lrnv\.julia\packages\Distributions\gggmX\src\univariate\locationscale.jl:144
 [6] top-level scope
   @ REPL[429]:1

julia> 
```

It would be usefull to do so in a `MixtureModel`, where each term of the mixture might have a different affine transformation applied to it. In particular, I would expect to be able to do the following: 

```
MixtureModel([Normal(0,1),6 - Gamma(1,1)],[1/2,1/2])
```

Is there another way to express this distribution or do I have to re-implement the mixture by hand ?

### PR DESCRIPTION
**Pull request by ParadaCarleton**
Closes #1653

### CODE REVIEW

File: test/univariate/locationscale.jl [hunk 1]
```diff
@@ -147,23 +147,23 @@ end
...
+        test_location_scale_discretenonparametric(_rng, -1//4, sign * 1//3, (-10):(-1), probs)
+        test_location_scale_discretenonparametric(_rng, 6//5, sign * 3//2, 15:24, probs)
     end
 
-    @test_logs Distributions.AffineDistribution(1.0, 1, Normal())
+    @test_logs AffineDistribution(1.0, 1, Normal())
 
-    @test_deprecated ls_norm = LocationScale(1.0, 1, Normal())
-    @test ls_norm isa LocationScale{Float64, Continuous, Normal{Float64}}
+    ls_norm = AffineDistribution(1.0, 1, Normal())
```
Comment (devmotion) [inline test/univariate/locationscale.jl:166]: Revert, this tests deprecated constructors:
```suggestion
    ls_norm = LocationScale(1.0, 1, Normal())
```

File: test/univariate/locationscale.jl [hunk 2]
```diff
@@ -147,23 +147,23 @@ end
...
+    @test ls_norm isa AffineDistribution{Float64, Continuous, Normal{Float64}}
```
Comment (devmotion) [inline test/univariate/locationscale.jl:167]: Revert, this checks that changes are non-breaking ans dispatches with `LocationScale` still work correctly:
```suggestion
    @test ls_norm isa LocationScale{Float64, Continuous, Normal{Float64}}
```

**Review by devmotion — CHANGES_REQUESTED** [review]

File: src/univariate/locationscale.jl [hunk 3]
```diff
@@ -106,36 +107,54 @@ mode(d::AffineDistribution) = d.μ + d.σ * mode(d.ρ)
...
+std(d::AffineDistribution) = abs(d.σ) * std(d.ρ)
+skewness(d::AffineDistribution) = sign(d.σ) * skewness(d.ρ)
 kurtosis(d::AffineDistribution) = kurtosis(d.ρ)
 
 isplatykurtic(d::AffineDistribution) = isplatykurtic(d.ρ)
 isleptokurtic(d::AffineDistribution) = isleptokurtic(d.ρ)
 ismesokurtic(d::AffineDistribution) = ismesokurtic(d.ρ)
 
-entropy(d::ContinuousAffineDistribution) = entropy(d.ρ) + log(d.σ)
+entropy(d::ContinuousAffineDistribution) = entropy(d.ρ) + log(abs(d.σ))
```
[the remark this answers is not in the document]
Comment (ParadaCarleton) [reply src/univariate/locationscale.jl:118]: Yes, but it returns a tuple `(log(abs(det(x))), sign(x))` rather than just the log of the magnitude.

[the remark this answers is not in the document]
Comment (devmotion) [reply src/univariate/locationscale.jl:119]: I see 👍

File: src/univariate/locationscale.jl [hunk 4]
```diff
@@ -106,36 +107,54 @@ mode(d::AffineDistribution) = d.μ + d.σ * mode(d.ρ)
...
+        return cdf(d.ρ, x)
+    end
+end
+
+quantile(d::AffineDistribution, q::Real) = d.μ + d.σ * quantile(d.ρ, d.σ > 0 ? q : 1 - q)
 
 rand(rng::AbstractRNG, d::AffineDistribution) = d.μ + d.σ * rand(rng, d.ρ)
-cf(d::AffineDistribution, t::Real) = cf(d.ρ,t*d.σ) * exp(1im*t*d.μ)
-gradlogpdf(d::ContinuousAffineDistribution, x::Real) = gradlogpdf(d.ρ,(x-d.μ)/d.σ) / d.σ
+gradlogpdf(d::ContinuousAffineDistribution, x::Real) =
```
[the remark this answers is not in the document]
Comment (devmotion) [reply src/univariate/locationscale.jl:156]:
```suggestion
cf(d::AffineDistribution, t::Real) = cf(d.ρ,t*d.σ) * exp(1im*t*d.μ)
gradlogpdf(d::ContinuousAffineDistribution, x::Real) = gradlogpdf(d.ρ,(x-d.μ)/d.σ) / d.σ
```

File: src/univariate/locationscale.jl [hunk 5]
```diff
@@ -106,36 +108,53 @@ mode(d::AffineDistribution) = d.μ + d.σ * mode(d.ρ)
...
 end
 
-quantile(d::AffineDistribution,q::Real) = d.μ + d.σ * quantile(d.ρ,q)
+quantile(d::AffineDistribution, q::Real) = d.μ + d.σ * quantile(d.ρ, d.σ > 0 ? q : 1 - q)
 
 rand(rng::AbstractRNG, d::AffineDistribution) = d.μ + d.σ * rand(rng, d.ρ)
-cf(d::AffineDistribution, t::Real) = cf(d.ρ,t*d.σ) * exp(1im*t*d.μ)
-gradlogpdf(d::ContinuousAffineDistribution, x::Real) = gradlogpdf(d.ρ,(x-d.μ)/d.σ) / d.σ
+gradlogpdf(d::ContinuousAffineDistribution, x::Real) =
+    gradlogpdf(d.ρ, (x-d.μ)/d.σ) / d.σ
```
Comment (devmotion) [inline src/univariate/locationscale.jl:157]:
```suggestion
```

File: src/univariate/locationscale.jl [hunk 6]
```diff
@@ -106,36 +114,52 @@ mode(d::AffineDistribution) = d.μ + d.σ * mode(d.ρ)
...
-logpdf(d::ContinuousAffineDistribution,x::Real) = logpdf(d.ρ,(x-d.μ)/d.σ) - log(d.σ)
+logpdf(d::ContinuousAffineDistribution,x::Real) = logpdf(d.ρ,(x-d.μ)/d.σ) - log(abs(d.σ))
 logpdf(d::DiscreteAffineDistribution, x::Real) = logpdf(d.ρ,(x-d.μ)/d.σ)
 
-for f in (:cdf, :ccdf, :logcdf, :logccdf)
-    @eval $f(d::AffineDistribution, x::Real) = $f(d.ρ, (x - d.μ) / d.σ)
+# CDF methods
+
+const CDF_FNS = (:cdf, :logcdf, :logccdf, :ccdf)
+for (f, fc) in zip(CDF_FNS, reverse(CDF_FNS))
```
Comment (devmotion) [inline src/univariate/locationscale.jl:142]:
```suggestion
for (f, fc) in ((:cdf, :ccdf), (:ccdf, :cdf), (:logcdf, :logccdf), (:logccdf, :logcdf))
```

File: src/univariate/locationscale.jl [hunk 7]
```diff
@@ -106,36 +114,52 @@ mode(d::AffineDistribution) = d.μ + d.σ * mode(d.ρ)
...
+    @eval function $f(d::ContinuousAffineDistribution, x::Real)
+        x = (x - d.μ) / d.σ
+        return d.σ > 0 ? $f(d.ρ, x) : $fc(d.ρ, x)
+    end
 end
 
-quantile(d::AffineDistribution,q::Real) = d.μ + d.σ * quantile(d.ρ,q)
+function cdf(d::DiscreteAffineDistribution, x::Real)
+    x = (x - d.μ) / d.σ
```
Comment (devmotion) [inline src/univariate/locationscale.jl:150]: The new `x` is something else, possibly even of a different type. It's confusing to use the same name.
```suggestion
    z = (x - d.μ) / d.σ
```

File: src/univariate/locationscale.jl [hunk 8]
```diff
@@ -106,36 +114,52 @@ mode(d::AffineDistribution) = d.μ + d.σ * mode(d.ρ)
...
+    # Have to include probability mass at endpoints
+    return d.σ > 0 ? cdf(d.ρ, x) : (ccdf(d.ρ, x) + pdf(d.ρ, x))
```
Comment (devmotion) [inline src/univariate/locationscale.jl:152]:
```suggestion
    return d.σ > 0 ? cdf(d.ρ, z) : (ccdf(d.ρ, z) + pdf(d.ρ, z))
```

File: src/univariate/locationscale.jl [hunk 9]
```diff
@@ -106,36 +114,52 @@ mode(d::AffineDistribution) = d.μ + d.σ * mode(d.ρ)
...
+end
+ccdf(d::DiscreteAffineDistribution, x::Real) = 1 - cdf(d, x)
```
Comment (devmotion) [inline src/univariate/locationscale.jl:154]: This is different from the current definitions - currently we do not use the default 1 - cdf.
```suggestion
function ccdf(d::DiscreteAffineDistribution, x::Real)
    z = (x - d.μ) / d.σ
    # Have to exlude probability mass at endpoints
    return d.σ > 0 ? ccdf(d.ρ, z) : (cdf(d.ρ, z) - pdf(d.ρ, x))
end
```

File: src/univariate/locationscale.jl [hunk 10]
```diff
@@ -106,36 +114,52 @@ mode(d::AffineDistribution) = d.μ + d.σ * mode(d.ρ)
...
+logcdf(d::DiscreteAffineDistribution, x::Real) = log(cdf(d, x))
```
Comment (devmotion) [inline src/univariate/locationscale.jl:155]: Also here the point is to not use this default.

File: src/univariate/locationscale.jl [hunk 11]
```diff
@@ -106,36 +114,52 @@ mode(d::AffineDistribution) = d.μ + d.σ * mode(d.ρ)
...
+logccdf(d::DiscreteAffineDistribution, x::Real) = log(ccdf(d, x))
```
Comment (devmotion) [inline src/univariate/locationscale.jl:156]: Same here, do not use thia default fallback.

**Review by devmotion — CHANGES_REQUESTED** [review]

File: src/univariate/locationscale.jl (hunk 10 above)
Comment (devmotion) [reply src/univariate/locationscale.jl:155]:
```suggestion
function logcdf(d::DiscreteAffineDistribution, x::Real)
    z = (x - d.μ) / d.σ
    return d.σ > 0 ? logcdf(d.ρ, z) : logaddexp(logccdf(d.ρ, z), logpdf(d.ρ, z))
```

File: src/univariate/locationscale.jl (hunk 11 above)
Comment (devmotion) [reply src/univariate/locationscale.jl:156]:
```suggestion
function logccdf(d::DiscreteAffineDistribution, x::Real)
    z = (x - d.μ) / d.σ
    return d.σ > 0 ? logccdf(d.ρ, z) : logsubexp(logcdf(d.ρ, z), logpdf(d.ρ, z))
end
```

File: src/univariate/locationscale.jl [hunk 12]
```diff
@@ -106,36 +114,52 @@ mode(d::AffineDistribution) = d.μ + d.σ * mode(d.ρ)
...
 
-for f in (:cdf, :ccdf, :logcdf, :logccdf)
-    @eval $f(d::AffineDistribution, x::Real) = $f(d.ρ, (x - d.μ) / d.σ)
+# CDF methods
+
+const CDF_FNS = (:cdf, :logcdf, :logccdf, :ccdf)
+for (f, fc) in zip(CDF_FNS, reverse(CDF_FNS))
+    @eval function $f(d::ContinuousAffineDistribution, x::Real)
+        x = (x - d.μ) / d.σ
+        return d.σ > 0 ? $f(d.ρ, x) : $fc(d.ρ, x)
```
Comment (devmotion) [inline src/univariate/locationscale.jl:145]:
```suggestion
        z = (x - d.μ) / d.σ
        return d.σ > 0 ? $f(d.ρ, z) : $fc(d.ρ, z)
```

File: test/univariate/locationscale.jl [hunk 13]
```diff
@@ -147,23 +147,26 @@ end
...
+            test_location_scale_discretenonparametric(_rng, 1//3, sign * 1//2, 1:10, probs)
+            test_location_scale_discretenonparametric(_rng, -1//4, sign * 1//3, (-10):(-1), probs)
+            test_location_scale_discretenonparametric(_rng, 6//5, sign * 3//2, 15:24, probs)
+        end
     end
 
     @test_logs Distributions.AffineDistribution(1.0, 1, Normal())
 
-    @test_deprecated ls_norm = LocationScale(1.0, 1, Normal())
+    ls_norm = LocationScale(1.0, 1, Normal())
```
Comment (devmotion) [inline test/univariate/locationscale.jl:169]:
```suggestion
    @test_deprecated ls_norm = LocationScale(1.0, 1, Normal())
```

File: src/univariate/locationscale.jl [hunk 14]
```diff
@@ -73,15 +73,21 @@ const DiscreteAffineDistribution{T<:Real,D<:DiscreteUnivariateDistribution} = Af
...
+        return RealInterval(μ + σ * support.lb, μ + σ * support.ub)
+    else
+        return RealInterval(μ + σ * support.ub, μ + σ * support.lb)
+    end
 end
-affinedistribution_support(μ::Real, σ::Real, support) = μ .+ σ .* support
+affinedistribution_support(μ::Real, σ::Real, support) = σ > 0 ? μ .+ σ .* support : μ .+ σ .* reverse(support)
 
-AffineDistribution(μ::Real, σ::Real, d::AffineDistribution) = AffineDistribution(μ + d.μ * σ, σ * d.σ, d.ρ)
+AffineDistribution(μ::Real, σ::Real, d::AffineDistribution) = AffineDistribution(μ + σ * d.μ, σ * d.σ, d.ρ)
```
Comment (devmotion) [inline src/univariate/locationscale.jl:90]:
```suggestion
AffineDistribution(μ::Real, σ::Real, d::AffineDistribution) = AffineDistribution(μ + d.μ * σ, σ * d.σ, d.ρ)
```

**Comment by devmotion** [comment]
I applied some of the suggestions (mostly to remove unrelated changes) to speed up the review process since I think the generalization would be quite useful.

**Comment by ParadaCarleton** [comment]
Looks good to me!

**Comment by ParadaCarleton** [comment]
> I applied some of the suggestions (mostly to remove unrelated changes) to speed up the review process since I think the generalization would be quite useful.

Anything missing, or should I merge this?

**Comment by devmotion** [comment]
> Anything missing, or should I merge this?

No, please do not merge. Tests do not pass.

**Comment by ParadaCarleton** [comment]
> > Anything missing, or should I merge this?
> 
> No, please do not merge. Tests do not pass.

Right, thanks, I missed that (since tests on 1.3 were passing, and tests passed locally). Looks like in some versions/hardware there's a tiny bit of floating-point error that was causing trouble with tests that didn't have `atol` set. That's been corrected now.

**Review by devmotion — APPROVED** [review]
Looks good to me!
