### PR TITLE
Use fieldnames()

### LINKED ISSUE #410: Crash printing Truncated Distribution
et-imac-retina:~ sjbespa$ julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.0-pre+7105 (2015-08-30 15:16 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit 349a4e1* (0 days old master)
|__/                   |  x86_64-apple-darwin14.5.0

julia> using Distributions
INFO: Recompiling stale cache file /Users/sjbespa/.julia/lib/v0.4/Distributions.ji for module Distributions.
INFO: Recompiling stale cache file /Users/sjbespa/.julia/lib/v0.4/PDMats.ji for module PDMats.

julia> rng = Truncated(Normal(0,1),-2.75,2.75);

julia> rng
Truncated(Error showing value of type Distributions.Truncated{Distributions.Normal,Distributions.Continuous}:
ERROR: type DataType has no field names
 in show at /Users/sjbespa/.julia/v0.4/Distributions/src/truncate.jl:104
 in anonymous at show.jl:1269
 in with_output_limit at ./show.jl:1246
 in showlimited at show.jl:1268
 in writemime at replutil.jl:4
 in display at REPL.jl:115
 in display at REPL.jl:118
 in display at multimedia.jl:151
 in print_response at REPL.jl:135
 in print_response at REPL.jl:122
 in anonymous at REPL.jl:624
 in run_interface at ./LineEdit.jl:1610
 in run_frontend at ./REPL.jl:863
 in run_repl at ./REPL.jl:167
 in _start at ./client.jl:453

julia>

### PR DESCRIPTION
**Pull request by johnmyleswhite**
In 0.4, we should use `fieldnames` instead of accessing the `.names` field directly.

Closes #410 .

### CODE REVIEW

**Comment by lindahua** [comment]
Thanks.

File: src/show.jl [hunk 1]
```diff
@@ -45,7 +45,10 @@ function _use_multline_show(d::Distribution, pnames)
     end
     return (multline, namevals)
 end
-_use_multline_show(d::Distribution) = _use_multline_show(d, typeof(d).names)
+
+function _use_multline_show(d::Distribution)
+    _use_multline_show(d, fieldnames(typeof(d)))
```
Comment (andreasnoack) [inline src/show.jl]: Should have an `@compat` to avoid breaking 0.3.
