### PR TITLE
Ensure test dependencies are precompiled before distributing tests

### LINKED ISSUE #538: Tests fail on v0.5
On Mac, with the Julia 0.5 release, I got the following error:
```
ERROR: LoadError: On worker 4:
LoadError: can only precompile from node 1
 in compilecache at ./loading.jl:560
 in require at ./loading.jl:393
 in jlcall_require_22337 at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 in include_string at ./loading.jl:441
 in jlcall_include_string_30821 at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 in include_from_node1 at ./loading.jl:491
 in jlcall_include_from_node1_20125 at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 in #5 at /Users/ranjan/.julia/v0.5/Distributions/test/runtests.jl:44
 in #625 at ./multi.jl:1421
 in run_work_thunk at ./multi.jl:1001
 in macro expansion at ./multi.jl:1421 [inlined]
 in #624 at ./event.jl:68
while loading /Users/ranjan/.julia/v0.5/Distributions/test/continuous.jl, in expression starting on line 5
 in #remotecall_fetch#606(::Array{Any,1}, ::Function, ::Function, ::Base.Worker, ::String, ::Vararg{String,N}) at ./multi.jl:1070
 in remotecall_fetch(::Function, ::Base.Worker, ::String, ::Vararg{String,N}) at ./multi.jl:1062
 in #remotecall_fetch#609(::Array{Any,1}, ::Function, ::Function, ::Int64, ::String, ::Vararg{String,N}) at ./multi.jl:1080
 in remotecall_fetch(::Function, ::Int64, ::String, ::Vararg{Any,N}) at ./multi.jl:1080
 in #remotecall_pool#689(::Array{Any,1}, ::Function, ::Function, ::Function, ::WorkerPool, ::String, ::Vararg{String,N}) at ./workerpool.jl:93
 in remotecall_pool(::Function, ::Function, ::WorkerPool, ::String, ::Vararg{String,N}) at ./workerpool.jl:91
 in #remotecall_fetch#692(::Array{Any,1}, ::Function, ::Function, ::WorkerPool, ::String, ::Vararg{String,N}) at ./workerpool.jl:124
 in remotecall_fetch(::Function, ::WorkerPool, ::String, ::Vararg{String,N}) at ./workerpool.jl:124
 in (::Base.###697#698#700{WorkerPool,##5#6})(::Array{Any,1}, ::Function, ::String, ::Vararg{String,N}) at ./workerpool.jl:151
 in (::Base.##697#699)(::String, ::Vararg{String,N}) at ./workerpool.jl:151
 in macro expansion at ./asyncmap.jl:63 [inlined]
 in (::Base.##755#757{Base.AsyncCollector,Base.AsyncCollectorState})() at ./task.jl:360
 in sync_end() at ./task.jl:311
 in done(::Base.AsyncCollector, ::Base.AsyncCollectorState) at ./asyncmap.jl:124
 in pump_source(::Base.AsyncGenerator, ::Base.AsyncGeneratorState) at ./asyncmap.jl:185
 in next(::Base.AsyncGenerator, ::Base.AsyncGeneratorState) at ./asyncmap.jl:201
 in _collect(::UnitRange{Int64}, ::Base.AsyncGenerator, ::Base.HasEltype, ::Base.SizeUnknown) at ./array.jl:282
 in #pmap#714(::Bool, ::Int64, ::Void, ::Int64, ::Float64, ::Function, ::Void, ::Void, ::Void, ::Base.#pmap, ::WorkerPool, ::##5#6, ::Array{String,1}) at ./pmap.jl:121
 in pmap(::WorkerPool, ::Function, ::Array{String,1}) at ./pmap.jl:80
 in #pmap#726(::Array{Any,1}, ::Function, ::Function, ::Array{String,1}) at ./pmap.jl:146
 in pmap(::Function, ::Array{String,1}) at ./pmap.jl:146
 in include_from_node1(::String) at ./loading.jl:488
 in include_from_node1(::String) at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 in process_options(::Base.JLOptions) at ./client.jl:262
 in _start() at ./client.jl:318
 in _start() at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
while loading /Users/ranjan/.julia/v0.5/Distributions/test/runtests.jl, in expression starting on line 43
```
versioninfo()
```
Julia Version 0.5.0
Commit 3c9d753 (2016-09-19 18:14 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, broadwell)
```
I've saved the entire failure gist [here](https://gist.github.com/ranjanan/8de31db177d043dac955ca269a2a780c)

### PR DESCRIPTION
**Pull request by ararslan**
I've moved all `using` statements to runtests.jl and I've declared all test dependencies in test/REQUIRE. The hope is that this will fix #538 by ensuring that all modules used by tests are precompiled prior to running the tests in parallel.

### CODE REVIEW

File: test/binomial.jl [hunk 1]
```diff
@@ -1,6 +1,3 @@
-using Distributions
-using Base.Test
```
Comment (andreasnoack) [inline test/binomial.jl]: It's quite convenient that a test file can be run in isolation so I think we should keep these.

Comment (ararslan) [inline test/binomial.jl]: Okay, will do

**Comment by ranjanan** [comment]
Thanks @ararslan! Would you mind tagging a new release please?

**Comment by ararslan** [comment]
@ranjanan Release tagged, METADATA PR up now.

**Comment by ranjanan** [comment]
Awesome, thanks!
