### PR TITLE
Fix #1358

### LINKED ISSUE #1358: CI build failure with latest versions
Recent version (changes between `v0.25.6` which was OK and `v0.25.8` continuously fail our CI at https://github.com/JuliaPlots/Plots.jl.

We hit a failure here: https://github.com/JuliaPlots/StatsPlots.jl/blob/fadcdf7f2d9c91798b9a789b68835fa7896a2183/test/runtests.jl#L75

Reproducer
---------------
```julia
using Plots; gr()
using StatsPlots
using Distributions

main() = begin
  plot(Poisson(1))
  png("bug")
end

main()
```
Output
---------
```julia
ERROR: LoadError: MethodError: no method matching UnitRange(::Int64, ::Float64)
Closest candidates are:
  UnitRange(::T, ::T) where T<:Real at range.jl:289
Stacktrace:
  [1] yz_args(dist::Poisson{Float64})
    @ StatsPlots [...]/StatsPlots/yDVtk/src/distributions.jl:22
  [2] macro expansion
    @ [...]/StatsPlots/yDVtk/src/distributions.jl:31 [inlined]
  [3] apply_recipe(plotattributes::AbstractDict{Symbol, Any}, dist::Distribution)
    @ StatsPlots [...]/RecipesBase/92zOw/src/RecipesBase.jl:282
  [4] _process_userrecipes!(plt::Any, plotattributes::Any, args::Any)
    @ RecipesPipeline [...]/RecipesPipeline/a80Nu/src/user_recipe.jl:36
  [5] recipe_pipeline!(plt::Any, plotattributes::Any, args::Any)
    @ RecipesPipeline [...]/RecipesPipeline/a80Nu/src/RecipesPipeline.jl:70
  [6] _plot!(plt::Plots.Plot, plotattributes::Any, args::Any)
    @ Plots [...]/Plots/Bfn5f/src/plot.jl:204
  [7] plot(args::Any; kw::Any)
    @ Plots [...]/Plots/Bfn5f/src/plot.jl:89
  [8] plot
    @ [...]/Plots/Bfn5f/src/plot.jl:83 [inlined]
  [9] main()
    @ Main [...]/bug.jl:6
 [10] top-level scope
    @ [...]/bug.jl:10
in expression starting at [...]/bug.jl:10
```

### PR DESCRIPTION
**Pull request by devmotion**
Fixes https://github.com/JuliaStats/Distributions.jl/issues/1358.

### CODE REVIEW

File: src/univariates.jl [hunk 1]
```diff
@@ -646,7 +646,7 @@ macro _delegate_statsfuns(D, fpre, psyms...)
     pargs = [Expr(:(.), :d, Expr(:quote, s)) for s in psyms]
 
     # output type of `quantile` etc.
-    T = :($D isa DiscreteUnivariateDistribution ? Int : Real)
+    T = :($D <: DiscreteUnivariateDistribution ? Int : Real)
```
Comment (mschauer) [inline src/univariates.jl:649]: Is this overwritten somewhere for discrete distributions which are not supported on the integers?

Comment (devmotion) [reply src/univariates.jl:649]: No, but the macro that forwards calculations to StatsFuns is only used for discrete distributions with integer valued support.

Comment (devmotion) [reply src/univariates.jl:649]: This PR only fixes the issue that was introduced in 0.25.7 when the `eval` parts of the macro where removed but does not introduce any new behaviour.
