### PR TITLE
Revert a tiny part of #655

### LINKED ISSUE #671: Conversion error on Julia 0.6
From Travis:
```
INFO: Testing Distributions
Running tests:
	From worker 2:	    testing Distributions.CategoricalDirectSampler
	From worker 2:	    testing Distributions.AliasTable
ERROR: LoadError: On worker 2:
LoadError: MethodError: Cannot `convert` an object of type Base.Random.RangeGeneratorInt{UInt64,UInt64} to an object of type Base.Random.RangeGeneratorInt{Int64,UInt64}
This may have arisen from a call to the constructor Base.Random.RangeGeneratorInt{Int64,UInt64}(...),
since type constructors fall back to convert methods.
Type at /home/travis/.julia/v0.6/Distributions/src/samplers/categorical.jl:29
Type at /home/travis/.julia/v0.6/Distributions/src/samplers/categorical.jl:42
macro expansion at /home/travis/.julia/v0.6/Distributions/test/samplers.jl:32 [inlined]
anonymous at ./<missing>:?
include_string at ./loading.jl:515
include_from_node1 at ./loading.jl:572
include at ./sysimg.jl:14
#17 at /home/travis/.julia/v0.6/Distributions/test/runtests.jl:51
#106 at ./distributed/process_messages.jl:268
run_work_thunk at ./distributed/process_messages.jl:56
macro expansion at ./distributed/process_messages.jl:268 [inlined]
#105 at ./event.jl:73
while loading /home/travis/.julia/v0.6/Distributions/test/samplers.jl, in expression starting on line 29
```

### PR DESCRIPTION
**Pull request by andreasnoack**
Fixes #671. Supersedes #674.

Also fix a vectorization in tests to avoid a warning

### CODE REVIEW

**Comment by andreasnoack** [comment]
This one passes on 0.6. We have quite a bit of a backlog here so I'll suggest that we'll merge this PR fairly soon and restart the tests for #676 to get green lights on master and then restart the tests of the remaining PRs.

File: src/samplers/categorical.jl [hunk 1]
```diff
@@ -38,8 +38,7 @@ function AliasTable(probs::AbstractVector{T}) where T<:Real
     accp = Vector{Float64}(n)
     alias = Vector{Int}(n)
     StatsBase.make_alias_table!(probs, 1.0, accp, alias)
-    un = unsigned(n)
-    AliasTable(accp, alias, Base.Random.RangeGeneratorInt(one(un),un))
+    AliasTable(accp, alias, Base.Random.RangeGenerator(1:n))
```
Comment (ararslan) [inline src/samplers/categorical.jl]: Wasn't this deprecated?

Comment (andreasnoack) [reply src/samplers/categorical.jl]: I couldn't find it and
```julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.7.0-DEV.2268 (2017-10-22 07:04 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit 34aab027e7* (0 days old master)
|__/                   |  x86_64-apple-darwin17.2.0

julia> Base.Random.RangeGenerator(1:4)
Base.Random.RangeGeneratorInt{Int64,UInt64}(1, 0x0000000000000004, 0x00000000ffffffff)
```
so I assumed it wasn't. When should that have happened?

Comment (ararslan) [reply src/samplers/categorical.jl]: I have no idea, just thought I remembered it being deprecated. ¯\\\_(ツ)\_/¯ If it's not then this LGTM.
