### PR TITLE
fix mgf of NegativeBinomial

### LINKED ISSUE #1603: NegativeBinomial wrong mgf
The moment generating function of NegativeBinomial is wrong:
```julia
julia> using Revise, Distributions, ForwardDiff, Test

julia> d = NegativeBinomial(4, 0.2)
NegativeBinomial{Float64}(r=4.0, p=0.2)

julia> @test ForwardDiff.derivative(Base.Fix1(mgf, d), 0) ≈ mean(d)
Test Failed at REPL[3]:1
  Expression: ForwardDiff.derivative(Base.Fix1(mgf, d), 0) ≈ mean(d)
   Evaluated: 5.000000000000001 ≈ 16.0
```
From the code it seems that the implementation of the mgf confuses success and fail probability.

### PR DESCRIPTION
**Pull request by jw3126**
fix #1603

### CODE REVIEW

File: src/univariate/discrete/geometric.jl [hunk 1]
```diff
@@ -124,7 +124,7 @@ end
 
 function mgf(d::Geometric, t::Real)
     p = succprob(d)
-    p / (expm1(-t) + p)
+    p / (expm1(-t) + p) - t
```
Comment (devmotion) [inline src/univariate/discrete/geometric.jl:127]: Shouldn't this be reverted to
```suggestion
    p / (expm1(-t) + p)
```
(see e.g. https://en.wikipedia.org/wiki/Moment-generating_function#Examples)?

File: src/univariate/discrete/negativebinomial.jl [hunk 2]
```diff
@@ -128,7 +128,7 @@ end
 
 function mgf(d::NegativeBinomial, t::Real)
     r, p = params(d)
-    return ((1 - p) * exp(t))^r / (1 - p * exp(t))^r
+    return mgf(Geometric(p), t)^r
```
Comment (devmotion) [inline src/univariate/discrete/negativebinomial.jl:131]: I think that's wrong (see e.g. https://en.wikipedia.org/wiki/Moment-generating_function#Examples)? My guess would be it should be something like
```suggestion
    return (p / (1 - (1 - p) * exp(t)))^r
```

File: test/univariate/discrete/negativebinomial.jl [hunk 3]
```diff
@@ -7,6 +7,16 @@ using FiniteDifferences
...
 
 mydiffp(r, p, k) = r/p - k/(1 - p)
+@testset "issue #1603" begin
+    d = NegativeBinomial(4, 0.2)
+    @test ForwardDiff.derivative(Base.Fix1(mgf, d), 0) ≈ mean(d)
+    d = NegativeBinomial(1, 0.2)
+    @test ForwardDiff.derivative(Base.Fix1(mgf, d), 0) ≈ mean(d)
+    d = Geometric(0.2)
+    @test mgf(d, 0) ≈ 1
+    @test ForwardDiff.derivative(Base.Fix1(mgf, d), 0) ≈ mean(d)
```
Comment (devmotion) [inline test/univariate/discrete/negativebinomial.jl:17]: Could this be moved to test/univariate/discrete/geometric.jl instead?

File: src/univariate/discrete/geometric.jl (hunk 1 above)
Comment (devmotion) [reply src/univariate/discrete/geometric.jl:127]: I guess the tests for `Geometric` pass even with the (IMO) incorrect version since `-t` does not affect the derivative at 0.

File: src/univariate/discrete/negativebinomial.jl (hunk 2 above)
Comment (jw3126) [reply src/univariate/discrete/negativebinomial.jl:131]: There is a subtle point here and with your other comment. Namely there are two widespread ways to parametrize the Geometric distribution, see https://en.wikipedia.org/wiki/Geometric_distribution

What is called `k-1` in the wikipedia mgf table is called `k` in `Distributions.jl`
With the Distributions.jl parametrizations `NegativeBinomial` is a convolution power in the most straight forward fashion
https://github.com/JuliaStats/Distributions.jl/blob/aca39200d7e2288b571895a09d8e0ec34b8dcf83/src/convolution.jl#L37

This translates into the mgf of NegativeBinomial being a power of that of Geometric.

File: src/univariate/discrete/geometric.jl (hunk 1 above)
Comment (jw3126) [reply src/univariate/discrete/geometric.jl:127]: `-t` adds a `-1` to the derivative. This corresponds to shifting the expectation value by `1`. Which corresponds to chaning the `Geometric` parametrization from `k-1` to `k`. See also my comments below.

Comment (devmotion) [reply src/univariate/discrete/geometric.jl:127]: Ah, I completely missed the different parameterization here. However, AFAIK the linear transformation Y := X - 1 of a random variable X should result in M_Y(t) = exp(-t) * M_X(t) instead of a shift by -t. So it seems it should be something like in https://github.com/JuliaStats/Distributions.jl/pull/1604/files/1b75633699749011a03a6b0ec85c335a8281073a#r945207774 (without the `^r`), e.g.,
```suggestion
    p / (1 - (1 - p) * exp(t))
```
That would also correspond to the formula given on Wikipedia (https://en.wikipedia.org/wiki/Geometric_distribution, right column).

File: src/univariate/discrete/negativebinomial.jl (hunk 2 above)
Comment (devmotion) [reply src/univariate/discrete/negativebinomial.jl:131]: Thanks for the explanation. Also with the formula in https://github.com/JuliaStats/Distributions.jl/pull/1604/files/1b75633699749011a03a6b0ec85c335a8281073a#r945344615 both the code in the PR (calling `mgf(Geometric(p), t)`) and the suggestion above would be identical it seems.

File: test/univariate/discrete/negativebinomial.jl (hunk 3 above)
Comment (devmotion) [reply test/univariate/discrete/negativebinomial.jl:17]: Could you address this comment @jw3126?

File: src/univariate/discrete/geometric.jl (hunk 1 above)
Comment (jw3126) [reply src/univariate/discrete/geometric.jl]: Yes you are right, I was thinking about `cgf = log mgf` where `exp(t)` becomes `t`.

File: src/univariate/discrete/geometric.jl [hunk 4]
```diff
@@ -124,13 +124,12 @@ end
...
     p = succprob(d)
-    p / (expm1(-t) + p)
+    p / (1 - (1 - p) * exp(t))
 end
 
 function cf(d::Geometric, t::Real)
     p = succprob(d)
-    # replace with expm1 when complex version available
-    p / (exp(-t*im) - 1 + p)
+    p / (1 - (1 - p) * cis(t))
```
Comment (devmotion) [inline src/univariate/discrete/geometric.jl:132]: For the same reason as above, maybe use
```suggestion
    p / (p - (1 - p) * expm1(t*im))
```

File: test/univariate/discrete/geometric.jl [hunk 5]
```diff
@@ -0,0 +1,11 @@
...
+using Test
+using ForwardDiff
+
+@testset "Geometric mgf and k vs k-1 parametrization #1604" begin
+    d = Geometric(0.2)
+    @test mgf(d, 0) ≈ 1 atol = 10eps(Float64) rtol=0
+    @test cf(d, 0)  ≈ 1 atol = 10eps(Float64) rtol=0
+    @test ForwardDiff.derivative(Base.Fix1(mgf, d), 0) ≈ mean(d)
+    @test ForwardDiff.derivative(Base.Fix1(cf, d), 0) ≈ mean(d) * im
+end
```
Comment (devmotion) [inline test/univariate/discrete/geometric.jl:11]: Maybe we should check derivatives with FiniteDifferences instead since ForwardDiff sometimes silently returns wrong derivatives (https://github.com/JuliaStats/Distributions.jl/issues/1582) and finite differencing seems more reliable. It also avoids issues on old Julia versions mentioned below, I assume.

E.g., with the `expm1` changes above,
```suggestion
using FiniteDifferences

@testset "Geometric mgf and k vs k-1 parametrization #1604" begin
    d = Geometric(0.2)
    @test mgf(d, 0) == 1
    @test cf(d, 0) == 1

    fdm = central_fdm(5, 1)
    @test fdm(Base.Fix1(mgf, d), 0) ≈ mean(d)
    @test fdm(Base.Fix1(cf, d), 0) ≈ mean(d) * im
end
```

File: test/univariate/discrete/negativebinomial.jl [hunk 6]
```diff
@@ -7,6 +7,17 @@ using FiniteDifferences
...
 mydiffp(r, p, k) = r/p - k/(1 - p)
+@testset "issue #1603" begin
+    d = NegativeBinomial(4, 0.2)
+    @test ForwardDiff.derivative(Base.Fix1(mgf, d), 0) ≈ mean(d)
+    d = NegativeBinomial(1, 0.2)
+    @test ForwardDiff.derivative(Base.Fix1(mgf, d), 0) ≈ mean(d)
+    if VERSION >= v"1.6"
+        # ForwardDiff bug in old julia
+        @test ForwardDiff.derivative(Base.Fix1(cf, d), 0) ≈ mean(d) * im
+    end
```
Comment (devmotion) [inline test/univariate/discrete/negativebinomial.jl:18]: Same here:
```suggestion
    fdm = central_fdm(5, 1)
    @test fdm(Base.Fix1(mgf, d), 0) ≈ mean(d)
    d = NegativeBinomial(1, 0.2)
    @test fdm(Base.Fix1(mgf, d), 0) ≈ mean(d)
    @test fdm(Base.Fix1(cf, d), 0) ≈ mean(d) * im
```

File: test/univariates.jl [hunk 7]
```diff
@@ -127,13 +127,13 @@ function verify_and_test(D::Union{Type,Function}, d::UnivariateDistribution, dct
 
     try
         m = mgf(d,0.0)
-        @test m == 1.0
+        @test m ≈ 1.0 atol=10*eps(Float64) rtol=0
```
Comment (devmotion) [inline test/univariates.jl:130]: I think with the `expm1` suggestions above this could be reverted.
```suggestion
        @test m == 1.0
```

File: test/univariates.jl [hunk 8]
```diff
@@ -127,13 +127,13 @@ function verify_and_test(D::Union{Type,Function}, d::UnivariateDistribution, dct
...
     catch e
         isa(e, MethodError) || throw(e)
     end
     try
         c = cf(d,0.0)
-        @test c == 1.0
+        @test c ≈ 1.0 atol=10*eps(Float64) rtol=0
```
Comment (devmotion) [inline test/univariates.jl:136]: Same here:
```suggestion
        @test c == 1.0
```

File: src/univariate/discrete/geometric.jl [hunk 9]
```diff
@@ -124,13 +124,12 @@ end
 
 function mgf(d::Geometric, t::Real)
     p = succprob(d)
-    p / (expm1(-t) + p)
+    p / (1 - (1 - p) * exp(t))
```
[the remark this answers is not in the document]
Comment (jw3126) [reply src/univariate/discrete/geometric.jl]: Awesome this trick is very neat, thanks a lot for all the suggestions.

File: src/univariate/discrete/negativebinomial.jl [hunk 10]
```diff
@@ -126,15 +126,17 @@ function rand(rng::AbstractRNG, d::NegativeBinomial)
...
+    return laplace_transform(Geometric(p, check_args=false), t)^r
 end
 
 function cf(d::NegativeBinomial, t::Real)
     r, p = params(d)
-    return (((1 - p) * cis(t)) / (1 - p * cis(t)))^r
+    return cf(Geometric(p, check_args=false), t)^r
 end
+mgf(d::NegativeBinomial, t::Real) = laplace_transform(d, -t)
+cf(d::Geometric, t::Real) = laplace_transform(d, -t*im)
```
Comment (devmotion) [inline src/univariate/discrete/negativebinomial.jl:139]:
```suggestion
mgf(d::NegativeBinomial, t::Real) = laplace_transform(d, -t)
cf(d::NegativeBinomial, t::Real) = laplace_transform(d, -t*im)
```

**Review by devmotion — APPROVED** [review]
Thank you for these fixes!
