### PR TITLE
fixing error in xval function in gumbel.jl

### LINKED ISSUE #1858: Error in xval in gumbel
There is an error in the `xval` function in `gumbel`.

```
using Distributions
d = Gumbel()
Distributions.xval(d, 0.2)
```
gives

```
ERROR: UndefVarError: `x` not defined
```

### PR DESCRIPTION
**Pull request by ajshephard**
There is a typo in the `xval` function in `gumbel.jl`. This closes #1858

### CODE REVIEW

**Review by andreasnoack — COMMENTED** [review]
Please add a test as well. Is `xval` generally not tested across distributions?

File: src/univariate/continuous/gumbel.jl [hunk 1]
```diff
@@ -98,8 +98,17 @@ function logpdf(d::Gumbel, x::Real)
...
 
-quantile(d::Gumbel, p::Real) = d.μ - d.θ * log(-log(p))
+quantile(d::Gumbel, p::Real) = xval(d, -log(-log(p)))
+cquantile(d::Gumbel, p::Real) = xval(d, -log(-log1p(-p)))
+invlogcdf(d::Gumbel, lp::Real) = xval(d, -log(-lp))
+invlogccdf(d::Gumbel, lp::Real) = xval(d, -log(-log1mexp(lp)))
 
 gradlogpdf(d::Gumbel, x::Real) = expm1(-zval(d, x)) / d.θ
+
+mgf(d::Gumbel, t::Real) = gamma(1.0 - d.θ * t) * exp(d.μ * t)
```
Comment (devmotion) [inline src/univariate/continuous/gumbel.jl:112]: `Float64` literals cause undesired promotions when working with e.g. `Float32`:
```suggestion
mgf(d::Gumbel, t::Real) = gamma(1 - d.θ * t) * exp(d.μ * t)
```

File: src/univariate/continuous/gumbel.jl [hunk 2]
```diff
@@ -98,8 +98,17 @@ function logpdf(d::Gumbel, x::Real)
...
+cgf(d::Gumbel, t::Real) = loggamma(1.0 - d.θ * t) + d.μ * t
```
Comment (devmotion) [inline src/univariate/continuous/gumbel.jl:113]:
```suggestion
cgf(d::Gumbel, t::Real) = loggamma(1 - d.θ * t) + d.μ * t
```

File: src/univariate/continuous/gumbel.jl [hunk 3]
```diff
@@ -98,8 +98,17 @@ function logpdf(d::Gumbel, x::Real)
...
+cf(d::Gumbel, t::Real) = gamma(1.0 - im * d.θ * t) * exp(im * d.μ * t)
```
Comment (devmotion) [inline src/univariate/continuous/gumbel.jl:114]:
```suggestion
cf(d::Gumbel, t::Real) = gamma(1 - im * d.θ * t) * cis(d.μ * t)
```

**Review by devmotion — APPROVED** [review]
Thank you!
