### PR TITLE
Fix `quantile_bisect` with single point in bracketing interval

### LINKED ISSUE #1501: Sampling from truncated mixture model results in an error
Hi! I have Julia 1.7.3 and Distributions 0.25.45. The error is as follows:

~~~~
julia> dist = Truncated(MixtureModel(Normal, [(1.0, 0.0)]), 0, Inf);

julia> rand(dist, 10)
ERROR: AssertionError: cl <= p <= cr
Stacktrace:
  [1] quantile_bisect(d::MixtureModel{Univariate, Continuous, Normal, Categorical{Float64, Vector{Float64}}}, p::Float64, lx::Float64, rx::Float64, tol::Float64)
    @ Distributions ~/.julia/packages/Distributions/9Albf/src/quantilealgs.jl:13
  [2] quantile_bisect(d::MixtureModel{Univariate, Continuous, Normal, Categorical{Float64, Vector{Float64}}}, p::Float64, lx::Float64, rx::Float64)
    @ Distributions ~/.julia/packages/Distributions/9Albf/src/quantilealgs.jl:11
  [3] quantile(d::MixtureModel{Univariate, Continuous, Normal, Categorical{Float64, Vector{Float64}}}, p::Float64)
    @ Distributions ~/.julia/packages/Distributions/9Albf/src/mixtures/mixturemodel.jl:447
  [4] quantile
    @ ~/.julia/packages/Distributions/9Albf/src/truncate.jl:128 [inlined]
  [5] rand
    @ ~/.julia/packages/Distributions/9Albf/src/univariates.jl:157 [inlined]
  [6] _rand!(rng::Random._GLOBAL_RNG, sampler::Truncated{MixtureModel{Univariate, Continuous, Normal, Categorical{Float64, Vector{Float64}}}, Continuous, Float64}, A::Vector{Float64})
    @ Distributions ~/.julia/packages/Distributions/9Albf/src/univariates.jl:147
  [7] rand!
    @ ~/.julia/packages/Distributions/9Albf/src/univariates.jl:142 [inlined]
  [8] rand
    @ ~/.julia/packages/Distributions/9Albf/src/genericrand.jl:52 [inlined]
  [9] rand
    @ ~/.julia/packages/Distributions/9Albf/src/genericrand.jl:24 [inlined]
 [10] rand(s::Truncated{MixtureModel{Univariate, Continuous, Normal, Categorical{Float64, Vector{Float64}}}, Continuous, Float64}, dims::Int64)
    @ Distributions ~/.julia/packages/Distributions/9Albf/src/genericrand.jl:22
 [11] top-level scope
    @ REPL[21]:1
~~~~

### PR DESCRIPTION
**Pull request by devmotion**
Fixes #1501.

### CODE REVIEW

File: src/quantilealgs.jl [hunk 1]
```diff
@@ -1,16 +1,26 @@
...
+        return middle(lx)
+    end
+
     # base tolerance on types to support e.g. `Float32` (avoids an infinite loop)
     # ≈ 3.7e-11 for Float64
     # ≈ 2.4e-5 for Float32
-    tol::Real=(eps(Base.promote_typeof(float(lx), float(rx))))^(2 / 3),
-)
+    tol = eps(float(T))^(2 / 3)
+
```
Comment (devmotion) [inline src/quantilealgs.jl:18]:
```suggestion
```

File: test/mixture.jl [hunk 2]
```diff
@@ -276,4 +276,15 @@ end
             @test cdf(utot,x) ≈ cdf(utot,x)
         end
     end
+
+    # issue #1501
+    @testset "quantile of mixture with single component" begin
+        for T in (Float32, Float64)
+            d = MixtureModel(Normal{T}(T(1), T(0)))
```
Comment (devmotion) [inline test/mixture.jl:283]:
```suggestion
            d = MixtureModel([Normal{T}(T(1), T(0))])
```

File: src/quantilealgs.jl [hunk 3]
```diff
@@ -1,16 +1,25 @@
...
+        # For specific types such as `Float64` it is more performant than `oftype((lx + rx) / 2, lx)`
+        return middle(lx)
+    end
+
     # base tolerance on types to support e.g. `Float32` (avoids an infinite loop)
     # ≈ 3.7e-11 for Float64
     # ≈ 2.4e-5 for Float32
-    tol::Real=(eps(Base.promote_typeof(float(lx), float(rx))))^(2 / 3),
-)
+    tol = eps(float(T))^(2 / 3)
```
Comment (mschauer) [inline src/quantilealgs.jl:17]: That widens `Float32` to `Float64`, but this seems okay

File: src/quantilealgs.jl [hunk 4]
```diff
@@ -1,16 +1,25 @@
 # Various algorithms for computing quantile
 
-function quantile_bisect(
-    d::ContinuousUnivariateDistribution, p::Real, lx::Real, rx::Real,
+function quantile_bisect(d::ContinuousUnivariateDistribution, p::Real, lx::T, rx::T) where {T<:Real}
+    rx < lx && throw(ArgumentError("[$lx, $rx] is not a valid bracketing interval"))
```
[the remark this answers is not in the document]
Comment (devmotion) [reply src/quantilealgs.jl:4]:
```suggestion
    rx < lx && throw(ArgumentError("empty bracketing interval [$lx, $rx]"))
```

File: src/quantilealgs.jl (hunk 3 above)
Comment (devmotion) [reply src/quantilealgs.jl:17]: Ah true :+1: Since the line is changed anyway it might be a good opportunity to fix it:
```suggestion
    tol = cbrt(eps(float(T)))^2
```

**Comment by devmotion** [comment]
Thank you for the review @mschauer! I updated the PR according to your suggestions, is it good to go now?

**Comment by devmotion** [comment]
Thanks @mschauer! I would still prefer merging my PRs myself though :stuck_out_tongue: (Mainly due to the reasons mentioned in https://github.com/JuliaStats/Distributions.jl/pull/1487#issuecomment-1028095516)

**Comment by devmotion** [comment]
> But we can make that decision "go for merge" (one of the maintainers which aren't author) separate from "merging" (the author or the maintainer).

Yes, of course, the approval still has to be given by one or multiple reviewers, separate from merging the PR. The relevant section in ColPrac is https://colprac.sciml.ai/#reviewing-approving-and-merging-prs.

**Comment by devmotion** [comment]
That's how I understood your comment :slightly_smiling_face: I know and mentioned that we don't follow ColPrac (and I don't think we have to fully commit to it - BTW multiple approvals are not too uncommon even in projects that follow it more closely in my experience). But regardless of how many approvals we want to collect, approving a PR can be separate from merging a PR.

(#1339 was also a bit different since Seth doesn't have any merge rights, so the one who approves the PR (finally) has to merge the PR as well.)

**Comment by mschauer** [comment]
Ok, we can just the review comment function on Github to explicitly making a "concluding approval" freeing the author to merge themselves.
